# Generated by Django 3.2.7 on 2021-11-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20211027_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='herramientas', verbose_name='Imagen'),
        ),
    ]
