# Generated by Django 3.2.9 on 2022-02-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_cursos_unidades_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='videos/imagenes', verbose_name='Imagen'),
        ),
    ]
